name: dart_code_metrics
version: 6.0.0
description: MIT-licensed fork of dart_code_metrics
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ">=5.1.0 <5.13.0"
  analyzer_plugin: ">=0.11.0 <0.12.0"
  ansicolor: ^2.0.1
  args: ^2.0.0
  collection: ^1.16.0
  crypto: ^3.0.0
  dart_code_metrics_presets:
    git:
      url: https://github.com/androidseb/dart-code-metrics-presets.git
      ref: dcmp_mit_fork
  file: ^7.0.0
  glob: ^2.0.1
  html: ">=0.15.0 <1.0.0"
  http: ^1.1.0
  meta: ^1.7.0
  path: ^1.8.0
  platform: ^3.1.0 # overridden for lowest versions compatibility
  pub_updater: ^0.4.0
  source_span: ^1.8.0
  uuid: ^4.1.0
  xml: ^6.4.2
  yaml: ^3.1.0

dev_dependencies:
  coverage: ^1.0.2
  intl: ">=0.17.0 <0.19.0"
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
